### ISSUE TITLE
Does not support ipv6

### ISSUE THREAD

**Issue by etopian** [mdomi/hosts#1]
You need to merge with this fork:
https://github.com/krallin/hosts

As it stands this can't read ipv6 so it fails on my Ubuntu box.

**Comment by blimmer** [comment]
👍

**Comment by mdomi** [comment]
Missed this from a while back - just merged in from code from @krallin

**Comment by blimmer** [comment]
Thanks! Also - appreciate this script 🍻

**Comment by mdomi** [comment]
Closed with pull request
